version: '3.1'

services:
  
  api:
    build: .
    container_name: it-members-api
    ports:
      - 3333:3333
    restart: always
    volumes:
      - ./:/app

  db:
    image: mysql
    container_name: mysql-it-members
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "it_members"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    restart: always

volumes:
  db-volume: